version: "3"

services:
  v1.backend:
    build:
      context: ./backend
    depends_on:
      - v1.db
    env_file: ./backend/.env
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./backend:/backend-app

  v1.frontend:
    build:
      context: ./frontend
    command: yarn dev
    depends_on:
      - v1.backend
      - v1.authentication
    volumes:
      - ./frontend:/frontend-app
      - ./frontend/package.json:/frontend-app/package.json
      - ./frontend/yarn.lock:/frontend-app/yarn.lock
    ports:
      - "3000:3000"

  v1.authentication:
    build:
      context: ./authentication
    command: yarn dev
    env_file: ./authentication/.env
    depends_on:
      - v1.db
    ports:
      - "3030:3030"
    volumes:
      - ./authentication:/authentication-app
      - ./authentication/package.json:/authentication-app/package.json
      - ./authentication/yarn.lock:/authentication-app/yarn.lock

  v1.db:
    image: postgres:11.3-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
